sudo: required
services:
  - docker

before_install:
  - docker build -t keeganrowecycl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run keeganrowecycl/react-test npm test -- --coverage

after_success
  - docker build -t keeganrowecycl/multi-client ./client
  - docker build -t keeganrowecycl/multi-nginx ./nginx
  - docker build -t keeganrowecycl/multi-server ./server
  - docker build -t keeganrowecycl/multi-worker ./worker

  #Log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push images to Docker Hub
  - docker push keeganrowecycl/multi-client
  - docker push keeganrowecycl/multi-nginx
  - docker push keeganrowecycl/multi-server
  - docker push keeganrowecycl/multi-worker